version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-apline
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - /.backend:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - 4306:3306
    volumes: 
      
    networks:
      - laravel

  php:
    networks:
      - laravel